apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hello-route
spec:
  parentRefs:
    - name: gateway-dev
  hostnames:
    - "hello.sample.dev"
  rules:
    - backendRefs:
        - kind: Service
          name: hello-svc
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /
