apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-large
  labels:
    app: hello-large
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-large
      tier: web
  template:
    metadata:
      labels:
        app: hello-large
        tier: web
    spec:
      containers:
      - name: hello-app-large
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1500m
            memory: 4Gi
