apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: custom-metrics
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: custom-metrics-stackdriver-adapter
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
    cloud.google.com/gke-nodepool: pool01