apiVersion: skaffold/v4beta5
kind: Config
profiles:
- name: dev
  manifests:
    kustomize:
      paths:
        - overlays/dev
  customActions:
  - name: predeploy-action
    containers:
    - name: predeploy-echo
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", 'echo "this is a predeploy action"' ]
    executionMode:
      kubernetesCluster: {}

- name: prod
  manifests:
    kustomize:
      paths:
        - overlays/prod
