apiVersion: skaffold/v2beta16
kind: Config
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
        - overlays/dev
- name: prod
  deploy:
    kustomize:
      paths:
        - overlays/prod
