apiVersion: v1
kind: Service
metadata:
  name: llm-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: gemma2-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000