apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
 ports:
 - name: service
   port: 8080
   protocol: TCP
 selector:
   app: hello
 type: ClusterIP